sudo: required
services:
  - docker

before_install:
  - docker build -t aschwins/tictactoe -f Dockerfile.dev .

script:
  - docker run -e CI=true aschwins/tictactoe npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-eu-west-1-500710929234"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"
